#!/usr/bin/env python3
"""Validate data/regions/*.json and generate dist/ outputs (JSON, CSV, SQL)."""
import csv
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGIONS_DIR = ROOT / "data" / "regions"
DIST = ROOT / "dist"
COUNTRY = {"code": "TR", "name": "Türkiye", "name_en": "Turkey"}
EXPECTED_CITY_COUNT = 81
TYPES = {"state", "foundation"}

TR_MAP = str.maketrans("çğıöşüÇĞİÖŞÜâîûÂÎÛ", "cgiosuCGIOSUaiuAIU")


def slugify(text):
    return re.sub(r"[^a-z0-9]+", "-", text.translate(TR_MAP).lower()).strip("-")


def load():
    errors, cities = [], []
    for path in sorted(REGIONS_DIR.glob("*.json")):
        region = json.loads(path.read_text(encoding="utf-8"))
        for city in region["cities"]:
            city["region"] = region["region"]
            cities.append(city)
            for uni in city["universities"]:
                if uni.get("type") not in TYPES:
                    errors.append(f"{city['name']}: {uni.get('name')} invalid type {uni.get('type')!r}")
                if not str(uni.get("website", "")).startswith("https://"):
                    errors.append(f"{city['name']}: {uni.get('name')} website must start with https://")

    plates = [c["plate_code"] for c in cities]
    if sorted(plates) != list(range(1, EXPECTED_CITY_COUNT + 1)):
        missing = sorted(set(range(1, EXPECTED_CITY_COUNT + 1)) - set(plates))
        dupes = sorted({p for p in plates if plates.count(p) > 1})
        errors.append(f"plate codes wrong: missing={missing} duplicates={dupes}")

    names = [u["name"] for c in cities for u in c["universities"]]
    for dup in sorted({n for n in names if names.count(n) > 1}):
        errors.append(f"duplicate university: {dup}")
    return sorted(cities, key=lambda c: c["plate_code"]), errors


def build(cities):
    DIST.mkdir(exist_ok=True)
    uni_id = 0
    out_cities, flat = [], []
    for c in cities:
        unis = []
        for u in sorted(c["universities"], key=lambda u: u["name"]):
            uni_id += 1
            row = {"id": uni_id, "name": u["name"], "slug": slugify(u["name"]),
                   "type": u["type"], "website": u["website"]}
            unis.append(row)
            flat.append({**row, "city_id": c["plate_code"], "city": c["name"]})
        out_cities.append({"id": c["plate_code"], "plate_code": c["plate_code"], "name": c["name"],
                           "slug": slugify(c["name"]), "region": c["region"], "universities": unis})

    def dump(name, obj):
        (DIST / name).write_text(json.dumps(obj, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    dump("turkey.json", {"country": COUNTRY, "cities": out_cities})
    dump("cities.json", [{k: v for k, v in c.items() if k != "universities"} for c in out_cities])
    dump("universities.json", flat)

    with open(DIST / "universities.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["id", "name", "slug", "type", "website", "city_id", "city"])
        w.writeheader()
        w.writerows(flat)

    q = lambda s: "'" + str(s).replace("'", "''") + "'"
    sql = [
        "-- Generated by scripts/build.py",
        "CREATE TABLE IF NOT EXISTS cities (id INTEGER PRIMARY KEY, name VARCHAR(64) NOT NULL, slug VARCHAR(64) NOT NULL, region VARCHAR(64) NOT NULL);",
        "CREATE TABLE IF NOT EXISTS universities (id INTEGER PRIMARY KEY, city_id INTEGER NOT NULL REFERENCES cities(id), name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, type VARCHAR(16) NOT NULL, website VARCHAR(255));",
    ]
    sql += [f"INSERT INTO cities VALUES ({c['id']}, {q(c['name'])}, {q(c['slug'])}, {q(c['region'])});" for c in out_cities]
    sql += [f"INSERT INTO universities VALUES ({u['id']}, {u['city_id']}, {q(u['name'])}, {q(u['slug'])}, {q(u['type'])}, {q(u['website'])});" for u in flat]
    (DIST / "turkey.sql").write_text("\n".join(sql) + "\n", encoding="utf-8")
    return flat


if __name__ == "__main__":
    cities, errors = load()
    if errors:
        print("\n".join(errors))
        sys.exit(1)
    flat = build(cities)
    state = sum(u["type"] == "state" for u in flat)
    print(f"OK: {len(cities)} cities, {len(flat)} universities ({state} state, {len(flat) - state} foundation)")
